simpleweb/romulus-cli

- package.json
Version bump from `0.1.0` to `1.0.0`.
> 0.1.0 => 1.0.0

- package.json
Adds more details to the `package.json` for NPM purposes.
> Package.json Updates

- package.json
Version bump from `1.0.0` to `1.0.1`.
> 1.0.0 => 1.0.1

- package.json
Version bump from `1.0.1` to `1.0.2`.
> 1.0.1 => 1.0.2

- README.md
- test/romulus.test.js
* Ensure the tests have the correct name.
* Include a badge for the build status.
> Updates to tests

- README.md
Links to an example app created by Romulus.
> Link to example app

- package.json
Version bump to match the current release.
> Version bump from 1.0.3 -> 1.1.0

- generators/base/index.js
- generators/base/templates/index.js
- package.json
Fixes `react-navigation`, it was missing some new dep’s due to the new version.
> React navigation update

- generators/base/index.js
- generators/base/templates/@types/redux-action-buffer.d.ts
- generators/base/templates/@types/styled.d.ts
- generators/base/templates/App/Actions/App.ts
- generators/base/templates/App/Components/App/index.tsx
- generators/base/templates/App/Components/Button/index.tsx
- generators/base/templates/App/Components/Button/styles.ts
- generators/base/templates/App/Components/Layout/index.tsx
- generators/base/templates/App/Components/Layout/styles.ts
- generators/base/templates/App/Components/Text/index.tsx
- generators/base/templates/App/Components/Text/styles.ts
- generators/base/templates/App/Components/Utilities/Environment/index.tsx
- generators/base/templates/App/Components/Utilities/Environment/styles.ts
- generators/base/templates/App/Reducers/App.ts
- generators/base/templates/App/Screens/Main.tsx
- generators/base/templates/App/Screens/Styleguide.tsx
- generators/base/templates/App/Services/API/logging.ts
- generators/base/templates/App/Store/Middleware/Logger.ts
- generators/base/templates/App/index.tsx
Corrects all the type errors after compilation is now working.
> TypeScript implementation

- generators/base/templates/App/Sagas/RequestExample.test.ts
- generators/base/templates/App/Sagas/RequestExample.ts
- generators/base/templates/__mocks__/axios.ts
- generators/base/templates/utilities/test-utilities.js
- package.json
Tests for our sagas. Gives implementation example of mocking axios with TypeScript support + 2.3.0 release.
> Saga testing

- generators/base/templates/@types/index.d.ts
- generators/base/templates/App/Components/App/index.tsx
- generators/base/templates/App/Router.tsx
- generators/base/templates/App/Screens/Main.tsx
- generators/base/templates/App/Screens/Styleguide.tsx
- generators/screen/templates/index.tsx
It turns out that I missed a few other places that needed upgrading. These changes fixes those issues and also fix some Typescript compilation errors too.
> Updates to react-navigation changes

- generators/base/index.js
- generators/base/templates/@types/react-redux.d.ts
- generators/base/templates/App/Reducers/App.test.ts
This fixes TypeScript issues with the `redux-saga` option.
`@testing-library/react-native` still throws one implicit any issue but I’ve made a PR against their repository.
---
Thank you for taking the time to contribute ❤️
> TypeScript fixes

- generators/base/templates/App/Screens/Styleguide.tsx
- generators/base/templates/App/index.tsx
- generators/base/templates/index.js
- Remove hardcoded reference
- Update React Query support, fixes #134
Any further comments, technical explanation or questions to add?
---
> React Query fix

- generators/base/index.js
- generators/base/templates/App/Components/Button/styles.ts
- generators/base/templates/App/Components/Text/styles.ts
- generators/base/templates/App/Components/Utilities/Environment/styles.ts
- generators/base/templates/App/Router.tsx
- generators/base/templates/App/Store/Middleware/Logger.ts
- generators/base/templates/App/Theme.ts
- generators/base/templates/App/index.tsx
- generators/base/templates/utilities/test-utilities.js
Adds support for dark mode and changes blacklist to blocklist
> Misc fixes

- generators/base/index.js
- generators/base/templates/App/Components/Authentication/index.tsx
- generators/base/templates/App/Components/Authentication/reducer.ts
- generators/base/templates/App/Helpers/Keychain.ts
- generators/base/templates/App/Router.tsx
- generators/base/templates/App/Screens/Launch.tsx
- generators/base/templates/App/Screens/Login.tsx
- generators/base/templates/App/Screens/index.ts
- generators/base/templates/App/index.tsx
This adds in an authentication component that does the following...
- Provides generic `login`, `logout` and `register` functions for you to fill out according to your apps own authentication.
- Handles the persistence of a "token" to the keychain, so you can remain logged in. This token is intended to be swapped from a hard coded value to your own implementation.
- Adds new Launch and Login screens to demonstrate waiting for authentication to load and determine authentication state.
- Handles fading animation between Launch screen and then Login/Main screens to show example of using authentication state to handle routing
https://user-images.githubusercontent.com/713128/125090180-fb591d80-e0c6-11eb-89de-333482996992.mp4
> Authentication

- generators/base/index.js
- generators/base/templates/.husky/pre-commit
- package.json
Fixes #152 
* Updates the husky configuration to support the latest version of husky (v8)
> Hotfix: Updates the configuration to support husky v8

- .github/workflows/test.yml
* Sets up the workflow for testing on Github Actions.
> Feature: Adds in workflow for tests on GH actions

- README.md
* Updates the badge in the README for the build status.
* Previously, we were using Semaphore, but now we are using Github Actions.
> Hotfix: Update build status badge

- .changeset/famous-buttons-shop.md
- generators/base/templates/App/Sagas/RequestExample.ts
* Updates the types on the `RequestExample` saga
> Feature: Fix the types on the `RequestExample` saga

- .changeset/nice-drinks-jog.md
- README.md
- docs/commands.md
- generators/screen/templates/index.tsx
* Update the screen command to generate consistent layout.
* Update the commands documentation to reflect these changes.
> Feature: Update the screen command

- .changeset/fast-pandas-check.md
- CHANGELOG.md
- package.json
> RELEASING: Releasing 1 package(s)
